### ISSUE TITLE
Migration to angular version 11@latest

### ISSUE THREAD

**Issue by paulbuechner** [gquinteros93/angular-css-modules#7]
# Problem Description
After doing the migration steps for the **@latest release** of Angular framework (v11), some additionally steps are required to get the app running correctly.

- [x] Support for **postcss-loader@4.2.0** - Syntax applied 787f3a2ab31caef505509dd1e6f3cc163c33300e 4a571f42994dc2ad1aacc379e5137a68fe19aa78

I did some research by myself and created a fork on which migration steps/changes can be viewed on: [migration-branch](https://github.com/paul-buechner/angular-css-modules/tree/migration)

## Support for postcss-loader@4.2.0
Solving issues regarding the **postcss-loader** dependency there is an option to ignore the failing compilation by modifying the `tsconfig.json` as follows:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    ...
  },
  "angularCompilerOptions": {
    "enableIvy": false,
    ...
  }
}
```
After this is done we get the following error:
```
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
```
Starting the development server now gives no more errors, but the css/scss files aren't beeing included! [graphic](https://user-images.githubusercontent.com/45827409/105788815-7f887000-5f81-11eb-8085-440b918a37b6.png)

### Fixing Syntax [postcss-loader-changelog](https://github.com/webpack-contrib/postcss-loader/blob/master/CHANGELOG.md) [postcss-loader-syntax](https://github.com/webpack-contrib/postcss-loader#postcssoptions)
Now given the new syntax which it seems has to be applied, we can migrate `postcss-loader` dependency to the latest version, also requiring to install the latest version of `postcss`. Small syntax adjustments regarding the `extra-webpack.config.js` where applied 787f3a2ab31caef505509dd1e6f3cc163c33300e.

**Comment by paul-buechner** [comment]
## Adressing compilation issues
This might be usefull!

Hi, just an update for those who found this after **Angular 11.1.0** release:
You will probably need to use **AngularWebpackPlugin** instead of **AngularCompilerPlugin**.

For example in my case it looks like this:
```
import { AngularWebpackPlugin } from '@ngtools/webpack/src/ivy/plugin';
  ...
  const index = config.plugins?.findIndex((p) => {
    return p instanceof AngularWebpackPlugin;
  });
  if (index) {
    // @ts-expect-error pluginOptions is a private property
    const oldOptions = config.plugins?.[index].pluginOptions;
    oldOptions.directTemplateLoading = false;
    config.plugins?.splice(index);
    config.plugins?.push(new AngularWebpackPlugin(oldOptions));
  }
```

_Originally posted by @kmaraz in https://github.com/just-jeb/angular-builders/issues/842#issuecomment-764573237_

**Comment by paul-buechner** [comment]
# SCSS file not beeing loaded properly
Remaining issue is the improper loading of component based scss files, which are handled in `extra-webpack.config.js`.

The issue hasn't beeing addressed yet. Will add more information later. Current compiling status: [successfull compilation](https://user-images.githubusercontent.com/45827409/105788815-7f887000-5f81-11eb-8085-440b918a37b6.png)

Possible source of error: `extra-webpack.config.js` line 8 ff.
```
/*  SCSS EXTEND */
    const scssRule = config.module.rules.find(x => x.test.toString().includes('scss'));
    const postcssLoader = scssRule.use.find(x => x.loader.toString().includes('postcss-loader'));
    const pluginFunc = postcssLoader.options.postcssOptions.plugins;
    const newPluginFunc = function () {
        var plugs = pluginFunc.apply(this, arguments);
        plugs.splice(plugs.length - 1, 0, postcssModules({ generateScopedName: "[hash:base64:5]" }));
        return plugs;
    }
    postcssLoader.options.postcssOptions.plugins = newPluginFunc;
```

**Comment by mjheller** [comment]
Hi. Enjoyed the tutorial. The scss.json files arent auto generated in Angular 11, if delete the files that were generated in prior versions it gives the error 

Error: ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/posthtml-loader/lib/index.js):
PostHTML Loader:

ENOENT: no such file or directory, lstat '..\angular-css-modules\src\app/app.component.scss.json'

**Comment by paulbuechner** [comment]
Hi @mjheller,

I was able to reproduce this issue! As you can see we are currently busy working on a stable release for angular 11.

If you don't mind check out the stable releases [here](https://github.com/gquinteros93/angular-css-modules/releases). 

The actual problem is the compilation process... it seems like ivy wants to compile before the scss.json file is even generated. A fix may be disabling ahead of time compilation...?

Anyway, for now, it just works by restarting the build/compile process because the scss.json will be generated despite the error.

![grafik](https://user-images.githubusercontent.com/45827409/111299859-bcebae80-8650-11eb-86fe-57f5b08c9035.png)

**Comment by Parovka** [comment]
Hi, first of all thank you for this repo, great work!

Unfortunate I stumbled on the same problem, and I was wondering if this could be fixed and when we can expect it. I understand that this is not a commercial project, and you need some free spare time. But just wondering :)

As I understand it correctly you have 2 workaround options, but...
Because I'm working for a client on a project which used Angular Elements, and it needs the ivy compiler for a smaller bundle size, the site speed is highly important for us.
Also we use a build pipeline, building him twice isn't the best option either.
So I'm hoping if the problem could be fully solved without a workaround, that would be great!

**Comment by paulbuechner** [comment]
Hi @Parovka,

there are currently no other additions/improvements planned.... however, we have a PR in the pipeline which is going to fix some issues, but needs some more love... As we both are currently very busy we would really appreciate any help addressing the existing issues.
